export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROFILE = "GET_PROFILE";
export const LOADING_PROFILE = "LOADING_PROFILE";
export const NO_PROFILE_FOUND = "NO_PROFILE_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_ALL_PROFILES = "GET_ALL_PROFILES";
